image: elixir:1.8.1-alpine

services:
  - postgres:latest

variables:
  POSTGRES_DB: test_test
  POSTGRES_HOST: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: "postgres"
  MIX_ENV: "test"

before_script:
  - apt-get update && apt-get -y install postgresql-client
  - mix local.hex --force
  - mix local.rebar --force
  - mix archive.install hex phx_new 1.4.2
  - mix deps.get --only test
  - mix ecto.create
  - mix ecto.migrate

mix:
  script:
  - mix test